const langs = [
    { name: "Arabic", code: "ar"},
    { name: "Armenian", code: "hy"},
    { name: "Azerbaijani", code: "az"},
    { name: "Bengali", code: "bn"},
    { name: "Bosnian", code: "bs"},
    { name: "Bulgarian", code: "bg"},
    { name: "Croatian", code: "hr"},
    { name: "Czech", code: "cs"},
    { name: "Danish", code: "da"},
    { name: "Dutch", code: "nl"},
    { name: "English", code: "en"},
    { name: "Finnish", code: "fi"},
    { name: "French", code: "fr"},
    { name: "Georgian", code: "ka"},
    { name: "German", code: "de"},
    { name: "Greek", code: "el"},
    { name: "Hungarian", code: "hu"},
    { name: "Indonesian", code: "id"},
    { name: "Italian", code: "it"},
    { name: "Japanese", code: "ja"},
    { name: "Korean", code: "ko"},
    { name: "Kurdish Sorani"},
    { name: "Norwegain", code: "no"},
    { name: "Persian", code: "fa"},
    { name: "Polish", code: "pl"},
    { name: "Portuguese", code: "pt"},
    { name: "Portuguese (Brasil)", code: "pt-br"},
    { name: "Romanian", code: "ro"},
    { name: "Russian", code: "ru"},
    { name: "Serbian", code: "sr"},
    { name: "Simplified Chinese (China)", code: "zh-cn"},
    { name: "Slovak", code: "sk"},
    { name: "Spanish", code: "es"},
    { name: "Swedish", code: "sv"},
    { name: "Thai", code: "th"},
    { name: "Traditional Chinese (Taiwan)", code: "zh-tw"},
    { name: "Turkish", code: "tr"},
    { name: "Ukrainian", code: "uk"},
    { name: "Urdu", code: "ur"},
    { name: "Vietnamese", code: "vi"}
]
